# Generated by Django 3.0.5 on 2020-04-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spread', '0003_geohotspot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
