# Generated by Django 3.0.5 on 2020-04-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spread', '0004_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
