# Generated by Django 3.0.5 on 2020-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spread', '0005_auto_20200424_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geohotspot',
            name='address',
        ),
        migrations.RemoveField(
            model_name='geohotspot',
            name='city',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='loc', max_length=100),
            preserve_default=False,
        ),
    ]
