# Generated by Django 3.0.5 on 2020-04-24 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spread', '0006_auto_20200424_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geohotspot',
            name='user',
        ),
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 15, 15, 11, 435681, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
