# Generated by Django 3.0.5 on 2020-04-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spread', '0009_delete_hotspot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
